import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('桌面端笔记详情、设置和分享链接应以内联页面呈现', async () => {
    const appSource = await readFile(new URL('../src/App.jsx', import.meta.url), 'utf8')
    const noteListSource = await readFile(new URL('../src/components/NoteList.jsx', import.meta.url), 'utf8')
    const editorSource = await readFile(new URL('../src/components/Editor.jsx', import.meta.url), 'utf8')

    assert.equal(appSource.includes('CenteredModalShell'), false)
    assert.equal(appSource.includes('title="笔记详情"'), false)
    assert.equal(appSource.includes('title="设置中心"'), false)
    assert.equal(appSource.includes('title="分享链接管理"'), false)
    assert.equal(appSource.includes('data-note-detail-desktop="inline-canvas"'), true)
    assert.equal(appSource.includes('data-settings-desktop="inline-page"'), true)
    assert.equal(appSource.includes('data-share-links-desktop="inline-page"'), true)
    assert.equal(appSource.includes('const [draftNote, setDraftNote] = useState(null)'), true)
    assert.equal(appSource.includes('const activeNote = selectedNote || draftNote'), true)
    assert.equal(appSource.includes('onCreateNote={openDraftNote}'), true)
    assert.equal(appSource.includes('if (!selectedNote?.id) return'), true)
    assert.equal(appSource.includes('setDraftNote(null)'), true)
    assert.equal(appSource.includes('{activeNote && currentView !== \'settings\' && currentView !== \'shares\' && ('), true)
    assert.equal(appSource.includes('{activeNote && currentView !== \'settings\' && ('), false)
    assert.equal(appSource.includes('{activeNote && currentView !== \'settings\' && currentView !== \'shares\' && window.innerWidth < 768 && ('), false)
    assert.equal(appSource.includes("${activeNote ? 'hidden' : currentView === 'settings' || currentView === 'shares' || currentView === 'admin' ? 'hidden' : 'flex'}"), true)
    assert.equal(appSource.includes("currentView === 'settings' || currentView === 'shares' ? 'hidden md:flex'"), false)
    assert.equal(noteListSource.includes("onClick={() => onCreateNote({ title: '', content: '' })}"), false)
    assert.equal(appSource.includes('ml-auto h-full w-[min(40vw,620px)]'), false)
    assert.equal(appSource.includes('ml-auto h-full w-[min(44vw,720px)]'), false)
    assert.equal(appSource.includes('ml-auto h-full w-[min(42vw,700px)]'), false)
    assert.equal(editorSource.includes("data-note-detail-shell={isOverlayDrawer ? 'open-canvas' : undefined}"), true)
    assert.equal(editorSource.includes('data-note-detail-topbar="floating"'), true)
    assert.equal(editorSource.includes("data-note-detail-content={isOverlayDrawer ? 'paper' : undefined}"), true)
    assert.equal(editorSource.includes('open-canvas-editor-content'), true)
})

test('CenteredModalShell 应定义统一尺寸、圆角和内部滚动容器', async () => {
    const shellSource = await readFile(new URL('../src/components/CenteredModalShell.jsx', import.meta.url), 'utf8')
    const cssSource = await readFile(new URL('../src/index.css', import.meta.url), 'utf8')

    assert.equal(shellSource.includes('rounded-[28px]'), true)
    assert.equal(shellSource.includes('min(760px, calc(100vw - 160px))'), true)
    assert.equal(shellSource.includes('min(860px, calc(100vh - 36px))'), true)
    assert.equal(shellSource.includes('overflow-y-auto'), false)
    assert.equal(shellSource.includes('overflow-hidden'), true)
    assert.equal(shellSource.includes('bg-[#fbfcfe] dark:bg-[#18212c]'), false)
    assert.equal(shellSource.includes('bg-white dark:bg-[#111925]'), true)
    assert.equal(shellSource.includes('bg-[#fbfcfe]/96'), false)
    assert.equal(shellSource.includes('dark:bg-[#18212c]/96'), false)
    assert.equal(shellSource.includes('text-[28px]'), false)
    assert.equal(shellSource.includes('text-[24px] md:text-[26px]'), true)
    assert.equal(shellSource.includes('h-11 w-11'), false)
    assert.equal(shellSource.includes('h-10 w-10'), true)
    assert.equal(shellSource.includes('pt-5 pb-3'), false)
    assert.equal(shellSource.includes('pt-4 pb-2.5'), true)
    assert.equal(shellSource.includes('overflow-y-auto px-6 md:px-8 pt-3 md:pt-4 pb-6 md:pb-8'), false)
    assert.equal(shellSource.includes('overflow-hidden px-6 md:px-8 pt-3 md:pt-4 pb-6 md:pb-8'), false)
    assert.equal(shellSource.includes('overflow-hidden pt-3 md:pt-4 pb-6 md:pb-8'), false)
    assert.equal(shellSource.includes('overflow-hidden px-4 md:px-6 pt-3 md:pt-4 pb-6 md:pb-8'), true)
    assert.equal(shellSource.includes('data-centered-modal-shell="true"'), true)
    assert.equal(cssSource.includes("[data-centered-modal-shell='true'] .surface-card"), true)
    assert.equal(cssSource.includes('box-shadow: none;'), true)
    assert.equal(cssSource.includes('border-color: transparent;'), true)
})

test('桌面设置中心应使用工作区内联页面轨道并缩小主操作按钮，尽量首屏看完', async () => {
    const settingsSource = await readFile(new URL('../src/components/SettingsPage.jsx', import.meta.url), 'utf8')

    assert.equal(settingsSource.includes("data-settings-page={isOverlayDrawer ? undefined : 'inline'}"), true)
    assert.equal(settingsSource.includes("px-3 pt-2 pb-4 md:pl-16 md:pr-3 md:pt-5 md:pb-6"), true)
    assert.equal(settingsSource.includes("mr-auto h-full w-full max-w-[720px]"), true)
    assert.equal(settingsSource.includes("hidden md:flex h-12 items-center mb-2.5"), true)
    assert.equal(settingsSource.includes("hidden md:flex h-12 items-center justify-between mb-2.5"), false)
    assert.equal(settingsSource.includes("arrow_back"), false)
    assert.equal(settingsSource.includes("返回"), false)
    assert.equal(settingsSource.includes("max-w-[760px]"), false)
    assert.equal(settingsSource.includes("mx-auto h-full w-full max-w-[980px]"), false)
    assert.equal(settingsSource.includes("surface-card max-w-[680px] mx-auto"), false)
    assert.equal(settingsSource.includes("md:mb-2.5"), true)
    assert.equal(settingsSource.includes("md:min-h-[58px]"), true)
    assert.equal(settingsSource.includes("md:p-2.5"), true)
    assert.equal(settingsSource.includes("md:space-y-1.5"), true)
    assert.equal(settingsSource.includes('h-9 px-3.5 rounded-xl text-[12px] font-semibold bg-primary text-white hover:bg-blue-600 disabled:opacity-60 transition-colors inline-flex items-center justify-center'), true)
    assert.equal(settingsSource.includes('h-9 w-full rounded-xl text-[12px] font-semibold bg-primary text-white hover:bg-blue-600 inline-flex items-center justify-center gap-2'), true)
})

test('居中 modal 内容组件不应再额外包一层桌面大圆角半透明内板', async () => {
    const editorSource = await readFile(new URL('../src/components/Editor.jsx', import.meta.url), 'utf8')
    const settingsSource = await readFile(new URL('../src/components/SettingsPage.jsx', import.meta.url), 'utf8')
    const shareLinksSource = await readFile(new URL('../src/components/ShareLinksPage.jsx', import.meta.url), 'utf8')

    assert.equal(editorSource.includes("isOverlayDrawer ? 'max-w-none px-1 md:px-2 pt-5 md:pt-6 pb-20'"), false)
    assert.equal(editorSource.includes("isOverlayDrawer ? 'surface-card max-w-4xl bg-[#fbfcfe]/96 dark:bg-[#211d1b]/86 rounded-[28px] px-6 md:px-10 pt-7 md:pt-9 pb-8'"), false)
    assert.equal(settingsSource.includes("isOverlayDrawer ? 'h-full min-h-0 overflow-y-auto pt-6'"), false)
    assert.equal(settingsSource.includes("isOverlayDrawer ? 'h-full min-h-0 overflow-y-auto no-scrollbar px-1 md:px-0 pt-2 md:pt-1 pr-1 md:pr-1.5'"), true)
    assert.equal(shareLinksSource.includes("isOverlayDrawer ? 'h-full min-h-0 overflow-y-auto pt-6'"), false)
    assert.equal(shareLinksSource.includes("isOverlayDrawer ? 'h-full min-h-0 overflow-y-auto no-scrollbar px-1 md:px-0 pt-2 md:pt-1 pr-1 md:pr-1.5'"), true)
})

test('桌面笔记详情开放画布应使用浮动控件和无卡片正文', async () => {
    const editorSource = await readFile(new URL('../src/components/Editor.jsx', import.meta.url), 'utf8')
    const shellSource = await readFile(new URL('../src/components/CenteredModalShell.jsx', import.meta.url), 'utf8')
    const settingsSource = await readFile(new URL('../src/components/SettingsPage.jsx', import.meta.url), 'utf8')
    const shareLinksSource = await readFile(new URL('../src/components/ShareLinksPage.jsx', import.meta.url), 'utf8')

    assert.equal(editorSource.includes("isOverlayDrawer ? 'bg-white/72 dark:bg-[#111925] rounded-[20px] md:h-[56px] px-3 md:px-4 border border-[#e7edf5] dark:border-[#263241]'"), false)
    assert.equal(editorSource.includes("editor-stage flex-1 h-full min-h-0 flex flex-col overflow-hidden relative ${isOverlayDrawer ? 'md:px-1 md:pb-1' : 'md:p-6 md:pl-5'}"), false)
    assert.equal(editorSource.includes("editor-stage flex-1 h-full min-h-0 flex flex-col overflow-hidden relative ${isOverlayDrawer ? 'overlay-stage-reset note-detail-open-canvas bg-transparent md:px-3 md:pt-5 md:pb-6' : 'md:p-6 md:pl-5'}"), true)
    assert.equal(editorSource.includes("overlay-stage-reset"), true)
    assert.equal(editorSource.includes('data-note-detail-topbar="floating"'), true)
    assert.equal(editorSource.includes('grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)]'), true)
    assert.equal(editorSource.includes('bg-white/78'), true)
    assert.equal(editorSource.includes('flex items-center space-x-0.5 md:space-x-4 pl-2'), false)
    assert.equal(editorSource.includes('note-detail-paper max-w-[680px]'), true)
    assert.equal(editorSource.includes("isOverlayDrawer ? 'max-w-none px-1 md:px-1 pt-3 md:pt-2 pb-20'"), false)
    assert.equal(editorSource.includes("isOverlayDrawer ? 'max-w-none rounded-[24px] border border-[#e8eef5] bg-[#fdfefe] px-3 md:px-4 pt-4 md:pt-5 pb-20 dark:border-[#233142] dark:bg-[#101923]'"), false)
    assert.equal(editorSource.includes("isOverlayDrawer ? 'max-w-none rounded-[24px] border border-[#e8eef5] bg-[#fdfefe] px-3 md:px-4 pt-6 md:pt-7 pb-20 dark:border-[#233142] dark:bg-[#101923]'"), false)
    assert.equal(editorSource.includes("open-canvas-editor-content"), true)
    assert.equal(shellSource.includes('pt-6 pb-4'), false)
    assert.equal(shellSource.includes('pt-5 pb-3'), false)
    assert.equal(shellSource.includes('pt-4 pb-2.5'), true)
    assert.equal(settingsSource.includes('overflow-y-auto no-scrollbar'), true)
    assert.equal(shareLinksSource.includes('overflow-y-auto no-scrollbar'), true)
    assert.equal(settingsSource.includes('overlay-stage-reset'), true)
    assert.equal(shareLinksSource.includes('overlay-stage-reset'), true)
    assert.equal(shellSource.includes('data-centered-modal-shell="true"'), true)
})

test('桌面笔记详情顶部工具图标应清楚表达图片分享、附件和导出', async () => {
    const editorSource = await readFile(new URL('../src/components/Editor.jsx', import.meta.url), 'utf8')

    assert.equal(editorSource.includes('title="生成图片分享">\n                                    <span className="material-icons-outlined text-[20px] leading-none">image</span>'), true)
    assert.equal(editorSource.includes('title="插入附件">\n                                    <span className="material-icons-outlined text-[20px] leading-none">attach_file</span>'), true)
    assert.equal(editorSource.includes('title="导出文件"'), true)
    assert.equal(editorSource.includes('<span className="material-icons-outlined text-[20px] leading-none">file_download</span>'), true)
    assert.equal(editorSource.includes('<span className="material-icons-outlined text-[20px] leading-none">edit_square</span>'), false)
    assert.equal(editorSource.includes('<span className="material-icons-outlined text-[20px] leading-none">edit</span>'), false)
    assert.equal(editorSource.includes('<span className="material-icons-outlined text-[20px] leading-none">open_in_full</span>'), false)
})

test('桌面笔记详情左上导航应对齐首页分组栏并提供明确返回和标题截断', async () => {
    const editorSource = await readFile(new URL('../src/components/Editor.jsx', import.meta.url), 'utf8')

    assert.equal(editorSource.includes("overlay-stage-reset note-detail-open-canvas bg-transparent md:px-3 md:pt-5 md:pb-6"), true)
    assert.equal(editorSource.includes('data-note-detail-return-group="true"'), true)
    assert.equal(editorSource.includes('aria-label="返回首页"'), true)
    assert.equal(editorSource.includes('title="返回首页"'), true)
    assert.equal(editorSource.includes('arrow_back'), true)
    assert.equal(editorSource.includes('返回'), true)
    assert.equal(editorSource.includes('h-12 w-[312px] max-w-[calc(100vw-7rem)] min-w-0 overflow-hidden rounded-[24px] bg-white'), true)
    assert.equal(editorSource.includes('min-w-0 flex-1 truncate'), true)
    assert.equal(editorSource.includes('max-w-[560px]'), false)
    assert.equal(editorSource.includes('max-w-[320px]'), false)
})
