import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('桌面端首页卡片应包含参考图还原所需的主题和布局标记', async () => {
  const source = await readFile(new URL('../src/components/NoteList.jsx', import.meta.url), 'utf8')
  const previewSource = await readFile(new URL('../src/components/NotePreviewCard.jsx', import.meta.url), 'utf8')
  const css = await readFile(new URL('../src/index.css', import.meta.url), 'utf8')

  assert.equal(source.includes('<NotePreviewCard'), true)
  assert.equal(previewSource.includes('getDesktopCardTheme'), true)
  assert.equal(source.includes("style={{ background: getCardBackgroundFromColor(color.value, color.light || '#fff') }}"), true)
  assert.equal(previewSource.includes('desktop-note-card-media'), true)
  assert.equal(previewSource.includes('music_note'), true)
  assert.equal(previewSource.includes('movie'), true)
  assert.equal(previewSource.includes('mediaHeaderClass'), true)
  assert.equal(previewSource.includes('z-[2]'), true)
  assert.equal(previewSource.includes('mediaIconSizeClass'), true)
  assert.equal(previewSource.includes('mediaIconBadgeClass'), false)
  assert.equal(previewSource.includes("bg-[#2f3a52] border-b border-[#233049]"), true)
  assert.equal(previewSource.includes("text-white/95"), true)
  assert.equal(previewSource.includes('w-12 h-12'), false)
  assert.equal(css.includes('.media-cover-icon-strong'), false)
  assert.equal(previewSource.includes("contentPanelClass = isDark ? '' : 'bg-white/[0.96]'"), false)
  assert.equal(previewSource.includes('imageBodyPanelClass'), false)
  assert.equal(previewSource.includes('usesLegacyLightCard'), true)
  assert.equal(previewSource.includes('text-white/72'), true)
  assert.equal(source.includes('onInput={handleCustomColorChange}'), true)
  assert.equal(source.includes('rgba(31, 41, 64, 0.98)'), false)
  assert.equal(previewSource.includes('h-[76px]'), true)
  assert.equal(previewSource.includes('h-full'), true)
  assert.equal(previewSource.includes("linear-gradient(180deg, #274487 0%, #1f2940 46%, #1f2940 100%)"), false)
  assert.equal(previewSource.includes("border-[#2b3448] text-white"), true)
  assert.equal(source.includes("border-white/18"), false)
  assert.equal(css.includes('grid-template-columns: repeat(auto-fill, minmax(148px, 1fr));'), true)
  assert.equal(css.includes('gap: 5px;'), true)
  assert.equal(css.includes('.expanded-note-card {'), true)
  assert.equal(css.includes('height: 168px;'), true)
})
